#!/bin/bash

#SBATCH --account=FY150028
#SBATCH --job-name=test
#SBATCH --time=96:00:00 --qos=long
#SBATCH --partition=batch
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=16

module load cmake/3.20.3 intel/18.0.0.128 openmpi-intel/4.1 mkl/18.0.0.128

# mpirun -np 16 /ascldap/users/etpaler/dev/rlammps_skin_extrusion/build/lmp -in in.prep.lmp
mpirun -np 16 /ascldap/users/etpaler/dev/rlammps_skin_extrusion/build/lmp -in in.fluid_oxidation.lmp

